# vim ft=tmux

# ------------------------------------------------------------------    
# Session Manager :
# ------------------------------------------------------------------    

bind-key "C-s" display-popup \
    -d "#{pane_current_path}" \
    -w 80% -h 80% \
    -E "sesh connect $(sesh list | fzf )"
