
# Options : 
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"

set -g prefix C-Space
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on   
set -g mode-keys vi

# Appearance :
source-file "~/.config/tmux/assets/colors.conf"
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""
set -g window-status-format "#[fg=white,bold]#I:#W"
set -g window-status-current-format "#[fg=cyan,bold]#I:#W"
set-window-option -g window-status-separator " | "
set -g pane-border-style "fg=white,nobold"

# Binds :
unbind r
bind r source-file "~/.config/tmux/tmux.conf"

bind-key v split-window -v
bind-key s split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Better Vim Navigations
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\S+\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n M-h if-shell "$is_vim" "send-keys M-h" "select-pane -L"
bind-key -n M-j if-shell "$is_vim" "send-keys M-j" "select-pane -D"
bind-key -n M-k if-shell "$is_vim" "send-keys M-k" "select-pane -U"
bind-key -n M-l if-shell "$is_vim" "send-keys M-l" "select-pane -R"

bind-key -T copy-mode-vi M-h select-pane -L
bind-key -T copy-mode-vi M-j select-pane -D
bind-key -T copy-mode-vi M-k select-pane -U
bind-key -T copy-mode-vi M-l select-pane -R

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
