
# Options : 
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"

set -g prefix C-Space
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on   

# Appearance :
source-file "~/.config/tmux/assets/colors.conf"
# set -g status-position top
set -g status-justify right
set -g status-style "bg=default"
set -g status-interval 5
set -g status-right "<< #[fg=cyan, bold]#S"
set -g status-left ""
set -g window-status-format " #[fg=white,bold]#I:#W "
set -g window-status-current-format " #[fg=orange,bold]#I:#W "
set-window-option -g window-status-separator "|"
set -g pane-border-style "fg=white,nobold"

# Binds :
unbind r
bind r source-file "~/.config/tmux/tmux.conf"

bind-key s split-window -v
bind-key v split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Sessioner 
unbind f
bind-key -r f display-popup -E -w 80% -h 80% "$HOME/.config/tmux/scripts/sessioner.sh"
bind -n M-f display-popup -E -w 80% -h 80% "$HOME/.config/tmux/scripts/sessioner.sh"

bind-key k display-popup -E "tmux kill-session -t \"\$(tmux list-sessions -F '#S' | fzf)\""

# Better Vim Navigations
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\S+\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n M-h if-shell "$is_vim" "send-keys M-h" "select-pane -L"
bind-key -n M-j if-shell "$is_vim" "send-keys M-j" "select-pane -D"
bind-key -n M-k if-shell "$is_vim" "send-keys M-k" "select-pane -U"
bind-key -n M-l if-shell "$is_vim" "send-keys M-l" "select-pane -R"

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Copymode
setw -g mode-keys vi
bind-key -T copy-mode-vi Escape send-keys -X cancel

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key -T copy-mode-vi h send-keys -X cursor-left
bind-key -T copy-mode-vi j send-keys -X cursor-down
bind-key -T copy-mode-vi k send-keys -X cursor-up
bind-key -T copy-mode-vi l send-keys -X cursor-right

bind-key -T copy-mode-vi w send-keys -X next-word
bind-key -T copy-mode-vi b send-keys -X previous-word
bind-key -T copy-mode-vi e send-keys -X next-word-end

bind-key -T copy-mode-vi 0 send-keys -X start-of-line
bind-key -T copy-mode-vi ^ send-keys -X back-to-indentation
bind-key -T copy-mode-vi $ send-keys -X end-of-line

bind-key -T copy-mode-vi C-u send-keys -X halfpage-up
bind-key -T copy-mode-vi C-d send-keys -X halfpage-down

bind-key -T copy-mode-vi g send-keys -X history-top
bind-key -T copy-mode-vi G send-keys -X history-bottom

bind-key -T copy-mode-vi / send-keys -X search-forward
bind-key -T copy-mode-vi ? send-keys -X search-backward
bind-key -T copy-mode-vi n send-keys -X search-again
bind-key -T copy-mode-vi N send-keys -X search-reverse

bind-key Escape copy-mode
bind-key -n M-Escape copy-mode

bind-key p paste-buffer

# Copy to system clipboard (Linux, requires xclip)
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

bind-key -T copy-mode-vi M-h select-pane -L
bind-key -T copy-mode-vi M-j select-pane -D
bind-key -T copy-mode-vi M-k select-pane -U
bind-key -T copy-mode-vi M-l select-pane -R
