#output=<not set>
font='FiraCode Nerd Font:size=15'
dpi-aware=no
prompt=" "
match-mode=fuzzy
terminal=ghostty 

include=/home/aviral/.config/fuzzel/themes/noctalia

anchor=center
lines=10
width=40
tabs=3
horizontal-pad=4
vertical-pad=4
inner-pad=5

[dmenu]

[key-bindings]
delete-line-forward=none
prev-with-wrap=Control+k
next-with-wrap=Control+j
