backend = "wal"
color_space = "lch"
palette = "saliencedarkbalanced16"

check_contrast = true

[templates]

hyprpaper.template  = "hyprpaper.conf"
hyprpaper.target    = "~/.config/hypr/hyprpaper.conf"

ghostty.template    = "ghostty.conf"
ghostty.target      = "~/.config/ghostty/colors.conf"

neovim.template     = "neopywal.vim"
neovim.target       = "~/.cache/wallust/colors_neopywal.vim"

[hooks]
hyprpaper = "hyprctl hyprpaper reload"
