wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
}

monitor.bluez.rules = [
  {
    matches = [{ device.name = "bluez_card.B6_C2_D5_83_BF_6E" }]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_sink ]
        bluez5.codecs = [ sbc_xq sbc ]
      }
    }
  }
]
