# Base
foreground #eae1d4
background #16130b
selection_foreground #392f15
selection_background #d0be95

# Cursor
cursor #eae1d4
cursor_text_color #cfc5b4

# URL
url_color #adcfad


# Base 16 colors
color0 #18211e
color8 #737462

color1 #d4ac57
color9 #d4ac57

color2 #2c7e7c
color10 #2c7e7c

color3 #855c32
color11 #855c32

color4 #bbb78a
color12 #bbb78a

color5 #5e492e
color13 #5e492e

color6 #68a9a3
color14 #68a9a3

color7 #b0ac8f
color15 #ece3bd
