// AutoGenerated File by Matugen
pragma Singleton
import QtQuick
import Quickshell

Singleton {
    readonly property string base00: "{{ base16.base00.default.hex }}"
    readonly property string base01: "{{ base16.base01.default.hex }}"
    readonly property string base02: "{{ base16.base02.default.hex }}"
    readonly property string base03: "{{ base16.base03.default.hex }}"
    readonly property string base04: "{{ base16.base04.default.hex }}"
    readonly property string base05: "{{ base16.base05.default.hex }}"
    readonly property string base06: "{{ base16.base06.default.hex }}"
    readonly property string base07: "{{ base16.base07.default.hex }}"
    readonly property string base08: "{{ base16.base08.default.hex }}"
    readonly property string base09: "{{ base16.base09.default.hex }}"
    readonly property string base0A: "{{ base16.base0a.default.hex }}"
    readonly property string base0B: "{{ base16.base0b.default.hex }}"
    readonly property string base0C: "{{ base16.base0c.default.hex }}"
    readonly property string base0D: "{{ base16.base0d.default.hex }}"
    readonly property string base0E: "{{ base16.base0e.default.hex }}"
    readonly property string base0F: "{{ base16.base0f.default.hex }}"
}
