-- Auto-generated by Matugen

require('mini.base16').setup({
    palette = {
        base00 = '#16130b',
        base01 = '#110e07',
        base02 = '#1f1b13',
        base03 = '#4c4639',
        base04 = '#cfc5b4',
        base05 = '#eae1d4',
        base06 = '#343027',
        base07 = '#3d392f',

        base08 = '#ffb4ab',
        base09 = '#adcfad',
        base0A = '#d5c5a0',
        base0B = '#e4c36c',
        base0C = '#304d33',
        base0D = '#584400',
        base0E = '#51462a',
        base0F = '#93000a',
    },
    use_cterm = false,
    plugins = { default = true },
})
