# -------------------------------------------------------- 
# TMUX CONFIGURATION FILE:
# --------------------------------------------------------


# Importing Modules: 
source-file ~/.config/tmux/modules/options.conf
source-file ~/.config/tmux/modules/keybinds.conf
source-file ~/.config/tmux/modules/floats.conf
source-file ~/.config/tmux/modules/tmux_nav.conf
source-file ~/.config/tmux/modules/appearance.conf
source-file ~/.config/tmux/modules/session_mgr.conf

